[package]
name = "cqrs-4-rust-actix"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "actix-web integration for CQRS views"

[dependencies]
ddd-4-rust-core.workspace = true
ddd-4-rust-esc.workspace = true
cqrs-4-rust-core.workspace = true
cqrs-4-rust-esc.workspace = true
actix-web.workspace = true
async-trait.workspace = true
log.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-cron-scheduler.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono.workspace = true
ddd-4-rust-test.workspace = true

[lints]
workspace = true
