[package]
name = "cqrs-4-rust-test-support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Test utilities for cqrs-4-rust"
publish = false

[dependencies]
ddd-4-rust-core.workspace = true
cqrs-4-rust-core.workspace = true

[lints]
workspace = true
